import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { FAVORITES_KEY } from './types';
import { useState } from 'react';
import Header from './heade';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // const [session, setSession] = useState(localStorage.getItem(FAVORITES_KEY) | []);
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
};
export default RootLayout;
