import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React, { useContext } from 'react';
import Header from './components/header/header';
import { ContextProvider } from './components/provider/contextProvider';
import { AuthContext, AuthProvider } from './components/provider/AuthProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Image collections',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang='en'>
      <link rel='shortcut icon' href='/fav_ico.png' />
      <body className={inter.className}>
        <Header />
        <ContextProvider>
          <AuthProvider>{children}</AuthProvider>
        </ContextProvider>
      </body>
    </html>
  );
};
export default RootLayout;
