import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from './components/header/header';
import { ContextProvider } from './components/provider/contextProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // const [session, setSession] = useState(localStorage.getItem(FAVORITES_KEY) | []);
  return (
    <html lang='en'>
      <link rel='shortcut icon' href='/fav_ico.png' />
      <body className={inter.className}>
        <Header />
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
};
export default RootLayout;
